[package]
name = "lectito-cli"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "CLI tool for extracting readable content from web pages"
readme = "README.md"
repository = "https://github.com/stormlightlabs/lectito"
homepage = "https://github.com/stormlightlabs/lectito"
keywords = ["readability", "article", "extraction", "cli", "html"]
categories = ["command-line-utilities", "text-processing", "web-programming"]
authors = ["Owais J. <info@stormlightlabs.org>"]

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
clap_complete = "4.5"
owo-colors = "4.2.3"
tokio = { version = "1.42", features = ["rt-multi-thread", "macros"] }

lectito-core = { path = "../core" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.24"
