[package]
name = "lectito-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
owo-colors = "4.2.3"
tokio = { version = "1.42", features = ["rt-multi-thread", "macros"] }

lectito-core = { path = "../core" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.24"
